# Changes here will be overwritten by Copier.
_commit: 0.0.154
_src_path: https://codeberg.org/margau/copier-python-uv.git
code_dir: paperless_asn_qr_codes
container: false
forgejo_url: https://codeberg.org/entropia/paperless-asn-qr-codes
ignore_pylint: true
ignore_ruff: true
ignore_ruff_format: true
project_description: Code for generating paperless ASN labels with QR codes
project_name: paperless-asn-qr-codes
pypi_publish: true
pypi_publish_dev: true
scripts:
    paperless-asn-qr-code: paperless_asn_qr_codes.main:main
