name: blackbox

on:
  push:
    branches:
      - main
  # non-main branches are handled by pull_request
  pull_request:

jobs:
  test-blackbox:
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-uv:latest@sha256:4fbcf119090c8d72e5cc0a7190735cb70a5c2ffb3383659c77705b0ef1551a55

    steps:
      - uses: https://code.forgejo.org/actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0
      - name: create venv
        run: uv sync --locked
      - run: mkdir -p out
      - name: build a PDF
        run: uv run paperless-asn-qr-code 0 out/l4731_0.pdf
      - name: check that PDF was created
        run: test -f out/l4731_0.pdf
      - name: check that PDF is not empty
        run: test $(stat -c%s out/l4731_0.pdf) -gt 10000
        # TODO: In the future, we could do a automated "visual" comarision to a reference sheet here.
      - name: upload artifact
        uses: https://code.forgejo.org/forgejo/upload-artifact@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
        with:
          name: pdf-output
          path: ./out/
