name: commitlint

on:
  push:
    branches:
      - main
  # non-main branches are handled by pull_request
  pull_request:

jobs:
  commitlint-check:
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-commitlint:latest@sha256:3bccaaee89209053963f9412ba1e4ea2b1d9514e336531bf2905eb027ac5c7c4

    steps:
      - uses: https://code.forgejo.org/actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: commitlint --last --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose