name: lint

on:
  push:
  pull_request:

jobs:
  forgejo:
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-uv:latest@sha256:aea16b3e030fb4c31b60027fde6565c93d53718d816492521d083d5e63c0771c

    steps:
      - uses: https://code.forgejo.org/actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: check with ruff
        run: uv run ruff check paperless_asn_qr_codes || exit 0 
      - name: format with ruff
        run: uv run ruff format --check paperless_asn_qr_codes || exit 0 
      - name: check with pylint
        run: uv run pylint paperless_asn_qr_codes || exit 0 