name: lint

on:
  push:
    branches:
      - main
  # non-main branches are handled by pull_request
  pull_request:

jobs:
  lint-check:
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-uv:latest@sha256:589be07d9017971184484e9d5f6d4aa83d096033f29b85b8ad28d9eef54b37cf

    steps:
      - uses: https://code.forgejo.org/actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: check with ruff
        run: uv run ruff check paperless_asn_qr_codes 
      - name: format with ruff
        run: uv run ruff format --check paperless_asn_qr_codes 
      - name: check with pylint
        run: uv run pylint paperless_asn_qr_codes 