name: lint

on:
  push:
    branches:
      - main
  # non-main branches are handled by pull_request
  pull_request:

jobs:
  lint-check:
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-uv:latest@sha256:f643c867abb66b44f4ba2ff329c528e537671b4e7f269db664ce676ec5482d4c

    steps:
      - uses: https://code.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: check with ruff
        run: uv run ruff check paperless_asn_qr_codes 
      - name: format with ruff
        run: uv run ruff format --check paperless_asn_qr_codes 
      - name: check with pylint
        run: uv run pylint paperless_asn_qr_codes 