name: publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  # non-main branches are handled by pull_request
  pull_request:

jobs:
  build_publish:
    name: "Build (and Publish)"
    runs-on: docker
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
    container:
      image: codeberg.org/margau/buildenv-uv:latest@sha256:c5732f2bd412b4404cf01a78b8238eeae0d9ae62460ecc66647ec04dd669d5bf
    
    steps:
      - uses: https://code.forgejo.org/actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - name: cache restore
        uses: https://code.forgejo.org/actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: /tmp/.uv-cache
          key: uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ hashFiles('uv.lock') }}
            uv
      - name: Build the project
        run: uv build
      - name: Publish release to pypi
        run: uv publish
        if: "${{ startsWith(github.ref, 'refs/tags') }}"
        env:
          UV_PUBLISH_TOKEN: "${{ secrets.UV_PUBLISH_TOKEN }}"
      - name: Publish dev version to pypi
        run: uv publish
        if: "${{ github.ref == 'refs/heads/main' }}"
        env:
          UV_PUBLISH_TOKEN: "${{ secrets.UV_PUBLISH_TOKEN }}"
      - name: release notes
        if: "${{ startsWith(github.ref, 'refs/tags') }}"
        run: |
          git-cliff --current -o notes.md
        env:
          GITEA_REPO: "${{ forgejo.repository }}"
      - name: Upload release assets to Forgejo
        uses: https://code.forgejo.org/actions/forgejo-release@98265452477dafb3f0f27ba9c462c90b18cb44fd # v2.13.4
        if: "${{ startsWith(github.ref, 'refs/tags') }}"
        with:
          direction: upload
          release-dir: dist
          release-notes-file: notes.md
      - name: Minimize uv cache
        run: uv cache prune
      - name: cache save
        uses: https://code.forgejo.org/actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: /tmp/.uv-cache
          key: uv-${{ hashFiles('uv.lock') }}

  releasenotes-draft:
    name: "Draft Release Notes"
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-uv:latest@sha256:c5732f2bd412b4404cf01a78b8238eeae0d9ae62460ecc66647ec04dd669d5bf
    
    steps:
      - uses: https://code.forgejo.org/actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - name: draft release notes
        run: |
          git-cliff --unreleased
        env:
          GITEA_REPO: "${{ forgejo.repository }}"
