name: publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  # non-main branches are handled by pull_request
  pull_request:

jobs:
  build_publish:
    name: "Build (and Publish)"
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-uv:latest@sha256:ba79a4aee42607ae983dcab497448decf132e30dd185b005ab8369e7feeac77c
    
    steps:
      - uses: https://code.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Build the project
        run: uv build
      - name: Publish release to pypi
        run: uv publish
        if: "${{ startsWith(github.ref, 'refs/tags') }}"
        env:
          UV_PUBLISH_TOKEN: "${{ secrets.UV_PUBLISH_TOKEN }}"
      - name: Publish dev version to pypi
        run: uv publish
        if: "${{ github.ref == 'refs/heads/main' }}"
        env:
          UV_PUBLISH_TOKEN: "${{ secrets.UV_PUBLISH_TOKEN }}"
      - name: release notes
        if: "${{ startsWith(github.ref, 'refs/tags') }}"
        run: |
          git-cliff --current -o notes.md
        env:
          GITEA_REPO: "${{ forgejo.repository }}"
      - name: Upload release assets to Forgejo
        uses: https://code.forgejo.org/actions/forgejo-release@9ef8d3a17f0c09ca6864a337f748e9c038d1c820 # v2.11.1
        if: "${{ startsWith(github.ref, 'refs/tags') }}"
        with:
          direction: upload
          release-dir: dist
          release-notes-file: notes.md
  releasenotes-draft:
    name: "Draft Release Notes"
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-uv:latest@sha256:ba79a4aee42607ae983dcab497448decf132e30dd185b005ab8369e7feeac77c
    
    steps:
      - uses: https://code.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: draft release notes
        run: |
          git-cliff --unreleased
        env:
          GITEA_REPO: "${{ forgejo.repository }}"
