name: publish

on:
  push:
  pull_request:

jobs:
  forgejo:
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-uv:latest@sha256:aea16b3e030fb4c31b60027fde6565c93d53718d816492521d083d5e63c0771c
    
    steps:
      - uses: https://code.forgejo.org/actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0
      - name: Build the project
        run: uv build
      - name: Publish release to pypi
        run: uv publish
        if: "${{ startsWith(github.ref, 'refs/tags') }}"
        env:
          UV_PUBLISH_TOKEN: "${{ secrets.UV_PUBLISH_TOKEN }}"
      - name: Publish dev version to pypi
        run: uv publish
        if: "${{ github.ref == 'refs/heads/main' }}"
        env:
          UV_PUBLISH_TOKEN: "${{ secrets.UV_PUBLISH_TOKEN }}"