name: pytest

on:
  push:
    branches:
      - main
  # non-main branches are handled by pull_request
  pull_request:

jobs:
  pytest:
    runs-on: docker
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
    container:
      image: codeberg.org/margau/buildenv-uv:latest@sha256:5fe5329c217c5107242a2b04523f25facbfe0a9ff00f895fbf8f6334e239a7b0

    steps:
      - uses: https://code.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: cache restore
        uses: https://code.forgejo.org/actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: /tmp/.uv-cache
          key: uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ hashFiles('uv.lock') }}
            uv
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: run pytest
        run: uv run coverage run -m pytest -v || exit 0 
      - name: show coverage
        run: uv run coverage report -m
      - name: Minimize uv cache
        run: uv cache prune --ci
      - name: cache save
        uses: https://code.forgejo.org/actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: /tmp/.uv-cache
          key: uv-${{ hashFiles('uv.lock') }}