name: pytest

on:
  push:
    branches:
      - main
  # non-main branches are handled by pull_request
  pull_request:

jobs:
  pytest:
    runs-on: docker
    container:
      image: codeberg.org/margau/buildenv-uv:latest@sha256:aaaf8bd9bfbe276136de485eb397aad9dc569b0ae76473b12f16b0205fcf4be0

    steps:
      - uses: https://code.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: run pytest
        run: uv run pytest || exit 0 
